### ISSUE TITLE
Schedule a workflow run ... quarterly?

### ISSUE THREAD

**Issue by nfreear** [nfreear/accessibility-devops#5]
... As the workflow results expire / are deleted after 90 days!

```yaml
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Run at 12am daily.

job:
  ...
```

* https://crontab.guru/#1_*_5_1,4,7,10_* ;

..
